[package]
name = "synche"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
local-ip-address = "0.6.5"
notify = "8.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
tokio = { version = "1.44.2", features = ["full"] }
